// UX principles index — GENERATED from principles/*.md. Do not edit.
//
// The rule IDs defined in principles/COMMON.md (every brand) and in each
// brand's file, so the mobile app can check that the IDs its design doc cites
// exist in the release it pins. The rules themselves are prose, in
// principles/ in the babel-design-tokens repo.
//
// Pure Dart, like babel_contracts.dart: no Flutter import.

/// Every UX principle this release defines.
abstract final class BabelPrinciples {
  /// Scopes in file order: `common` (every brand), then each brand.
  static const List<String> scopes = <String>[
    'common',
    'babel',
  ];

  /// Rule ID → its scope.
  static const Map<String, String> scope = <String, String>{
    'FOCUS-1': 'common',
    'FOCUS-2': 'common',
    'FOCUS-3': 'common',
    'FOCUS-4': 'common',
    'PREVENT-1': 'common',
    'PREVENT-2': 'common',
    'PREVENT-3': 'common',
    'PREVENT-4': 'common',
    'PREVENT-5': 'common',
    'PREVENT-6': 'common',
    'FORM-1': 'common',
    'FORM-2': 'common',
    'FORM-3': 'common',
    'FORM-4': 'common',
    'FORM-5': 'common',
    'STATE-1': 'common',
    'STATE-2': 'common',
    'STATE-3': 'common',
    'STATE-4': 'common',
    'COPY-1': 'common',
    'COPY-2': 'common',
    'COPY-3': 'common',
    'COPY-4': 'common',
    'COPY-5': 'common',
    'COPY-6': 'common',
    'COPY-7': 'common',
    'TRUTH-1': 'common',
    'TRUTH-2': 'common',
    'LIST-1': 'common',
    'LIST-2': 'common',
    'LIST-3': 'common',
    'LIST-4': 'common',
    'CONFIRM-1': 'common',
    'CONFIRM-2': 'common',
    'CONFIRM-3': 'common',
    'A11Y-1': 'common',
    'A11Y-2': 'common',
    'A11Y-3': 'common',
    'A11Y-4': 'common',
    'A11Y-5': 'common',
    'A11Y-6': 'common',
    'VISUAL-1': 'common',
    'VISUAL-2': 'common',
    'VISUAL-3': 'common',
    'VISUAL-4': 'common',
    'VISUAL-5': 'common',
    'DATA-1': 'common',
    'DATA-2': 'common',
    'DONE-1': 'common',
    'DONE-2': 'common',
    'DONE-3': 'common',
    'DONE-4': 'common',
    'DONE-5': 'common',
    'DONE-6': 'common',
    'BABEL-ID-1': 'babel',
    'BABEL-ID-2': 'babel',
    'BABEL-ID-3': 'babel',
    'BABEL-ID-4': 'babel',
    'BABEL-ID-5': 'babel',
    'BABEL-FOCUS-1': 'babel',
    'BABEL-FOCUS-2': 'babel',
    'BABEL-DEVICE-1': 'babel',
    'BABEL-LANG-1': 'babel',
    'BABEL-LEGAL-1': 'babel',
    'BABEL-DATA-1': 'babel',
    'BABEL-HAPTIC-1': 'babel',
    'BABEL-CONFIRM-1': 'babel',
    'BABEL-DONE-1': 'babel',
  };

  /// Rule ID → its title.
  static const Map<String, String> title = <String, String>{
    'FOCUS-1': 'The object the user came for is in the first viewport',
    'FOCUS-2': 'Analysis sits below the object, never above it',
    'FOCUS-3': 'Nothing on screen only says something',
    'FOCUS-4': 'Fold prose, not verdicts',
    'PREVENT-1': 'An incomplete submit stays pressable and says what is missing',
    'PREVENT-2': 'Required fields are marked before any click',
    'PREVENT-3': 'Input limits are checked live, from the shared contract',
    'PREVENT-4': 'An action the server will refuse is hidden or disabled, with its reason',
    'PREVENT-5': 'Default only what the domain can stand behind',
    'PREVENT-6': 'Never default a legal fact',
    'FORM-1': 'A placeholder is not a label',
    'FORM-2': 'Scold late, praise early',
    'FORM-3': 'The submit button never moves',
    'FORM-4': 'Autofill is a state, and is styled',
    'FORM-5': 'A code is not a number',
    'STATE-1': 'Every data screen has four states',
    'STATE-2': 'A failed load is never shown as empty',
    'STATE-3': 'Pages shimmer, buttons spin',
    'STATE-4': 'An empty state says what to do next',
    'COPY-1': 'A refusal names its real gate',
    'COPY-2': 'An error code is as specific as the sentence it replaces',
    'COPY-3': 'Missing and zero are different facts',
    'COPY-4': 'One fact, one voice',
    'COPY-5': 'No user-visible string is hard-coded',
    'COPY-6': 'Money and dates go through the shared formatters',
    'COPY-7': 'Server messages never quote a UI control',
    'TRUTH-1': 'Show the server\'s decision; never re-derive it',
    'TRUTH-2': 'Shared vocabularies are imported, never re-typed',
    'LIST-1': 'Every visible status or category can be filtered',
    'LIST-2': 'A filter matches the raw value, never the translated label',
    'LIST-3': 'Never hide what signals money, time or identity',
    'LIST-4': 'A saved view stores only what the user changed',
    'CONFIRM-1': 'Every confirmation says whether it destroys something',
    'CONFIRM-2': 'A destructive dialog opens on Cancel',
    'CONFIRM-3': 'Feedback comes from the shared components',
    'A11Y-1': 'Text meets WCAG AA in every theme',
    'A11Y-2': 'Colour is never the only signal',
    'A11Y-3': 'Focus is always visible',
    'A11Y-4': 'Every control has a name',
    'A11Y-5': 'Touch targets are large enough',
    'A11Y-6': 'Disabled stays readable, and working is not disabled',
    'VISUAL-1': 'Tokens only',
    'VISUAL-2': 'Spend the role, not the number',
    'VISUAL-3': 'Every colour exists in light and dark',
    'VISUAL-4': 'Compose the shared components; never rebuild one',
    'VISUAL-5': 'Pinned headers are opaque',
    'DATA-1': 'Mask only what opens a door',
    'DATA-2': 'Inform about anomalies in users\' data; never act on them',
    'DONE-1': 'Done means seen working, not checks passing',
    'DONE-2': 'Verify at the hardest layout',
    'DONE-3': 'Read the rendered screen, not the source',
    'DONE-4': 'A screen that can correctly show nothing needs a positive control',
    'DONE-5': 'Never test in production',
    'DONE-6': 'A guard\'s limit only goes down',
    'BABEL-ID-1': 'Black core, bronze accent',
    'BABEL-ID-2': 'Bronze text uses the strong bronze',
    'BABEL-ID-3': 'Two voices: the manager\'s console and the resident\'s pocket tool',
    'BABEL-ID-4': 'Typefaces',
    'BABEL-ID-5': 'Shapes',
    'BABEL-FOCUS-1': 'Admin lists put the first row in view at 1280×800',
    'BABEL-FOCUS-2': 'Mobile screens lead with one verdict',
    'BABEL-DEVICE-1': 'The Pixel 2 is the mobile floor',
    'BABEL-LANG-1': 'Four locales, one key format',
    'BABEL-LEGAL-1': 'The legal facts Babel never defaults',
    'BABEL-DATA-1': 'What Babel masks and what it shows',
    'BABEL-HAPTIC-1': 'Five vibration tiers on mobile',
    'BABEL-CONFIRM-1': 'What counts as destructive in Babel',
    'BABEL-DONE-1': 'Smoke on dev, as the approved seats only',
  };
}
